[package]
name = "rec_aggregation"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
init-profile = ["lean_vm/init-profile"]
prox-gaps-conjecture = ["lean_prover/prox-gaps-conjecture"]
multibus-toy = ["lean_prover/multibus-toy", "lean_vm/multibus-toy"]

[dependencies]
xmss = { workspace = true, features = ["test-utils"] }
tracing.workspace = true
include_dir.workspace = true
sub_protocols.workspace = true
lean_vm.workspace = true
lean_compiler.workspace = true
lean_prover.workspace = true
backend.workspace = true
parallel.workspace = true
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
