# source: https://github.com/leanEthereum/leanSpec

from __future__ import annotations
from itertools import accumulate, repeat
from typing import Final, Sequence

P: Final = 2**31 - 2**24 + 1  # Koalabear prime
TWO_ADICITY = 24
MDS_FIRST_ROW_16: Final = (1, 1, 51, 1, 11, 17, 2, 1, 101, 63, 15, 2, 67, 22, 13, 3)  # for Poseidon
KB_TWO_ADIC_GENERATORS: Final = tuple(pow(0x6AC49F88, 1 << (TWO_ADICITY - b), P) for b in range(TWO_ADICITY + 1))

SPONGE_RATE, SPONGE_STATE, DIGEST_ELEMS = 8, 16, 8
SPONGE_CAPACITY = SPONGE_STATE - SPONGE_RATE


class Fp:
    """An element of the KoalaBear prime field `F_p`."""

    __slots__ = ("value",)

    def __init__(self, value: int) -> None:
        self.value = value % P

    def __add__(self, other: "Fp") -> "Fp":
        return Fp(self.value + other.value)

    def __sub__(self, other: "Fp") -> "Fp":
        return Fp(self.value - other.value)

    def __neg__(self) -> "Fp":
        return Fp(-self.value)

    def __mul__(self, other: "Fp") -> "Fp":
        return Fp(self.value * other.value)

    def __pow__(self, exponent: int) -> "Fp":
        return Fp(pow(self.value, exponent, P))

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Fp) and self.value == other.value

    def __hash__(self) -> int:
        return hash(self.value)

    def __repr__(self) -> str:
        return f"Fp(value={self.value})"


def quintic_mul(a, b, zero):
    """Schoolbook product in `Fp[X]/(X⁵+X²−1)`"""
    prod = [zero] * 9
    for i in range(5):
        for j in range(5):
            prod[i + j] = prod[i + j] + a[i] * b[j]
    for k in range(8, 4, -1):  # X^k = X^(k−5)·(1 − X²) for k ≥ 5.
        prod[k - 5] = prod[k - 5] + prod[k]
        prod[k - 3] = prod[k - 3] - prod[k]
    return prod[:5]


class EF:
    """Quintic extension `Fp[X] / (X⁵ + X² − 1)`."""

    __slots__ = ("c",)
    DIMENSION = 5

    def __init__(self, value):
        """Accepts an `int` (lifted via `Fp`), an `Fp` (lifted), or a length-5 `Sequence[Fp]`."""
        if isinstance(value, int):
            self.c = (Fp(value), Fp(0), Fp(0), Fp(0), Fp(0))
        elif isinstance(value, Fp):
            self.c = (value, Fp(0), Fp(0), Fp(0), Fp(0))
        else:
            assert len(value) == 5
            self.c = tuple(value)

    def __add__(self, o):
        if isinstance(o, int):
            return self if o == 0 else self + EF(o)
        if isinstance(o, Fp):
            return EF([self.c[0] + o, *self.c[1:]])
        return EF([a + b for a, b in zip(self.c, o.c)])

    def __sub__(self, o):
        if isinstance(o, Fp):
            return EF([self.c[0] - o, *self.c[1:]])
        return EF([a - b for a, b in zip(self.c, o.c)])

    def __neg__(self):
        return EF([-a for a in self.c])

    __radd__ = __add__

    def __mul__(self, o):
        if isinstance(o, int):
            return self if o == 1 else self * EF(o)
        if isinstance(o, Fp):
            return EF([a * o for a in self.c])
        return EF(quintic_mul(self.c, o.c, Fp(0)))

    __rmul__ = __mul__

    def __eq__(self, o):
        return isinstance(o, EF) and self.c == o.c

    def __hash__(self):
        return hash(self.c)

    def __repr__(self):
        return f"EF({[int(x.value) for x in self.c]})"

    def inv(self) -> "EF":
        result, base, n = ONE, self, P**5 - 2
        while n > 0:
            if n & 1:
                result = result * base
            base = base * base
            n >>= 1
        return result


ZERO = EF(0)
ONE = EF(1)


def ef_powers(x: EF, n: int) -> list[EF]:
    """`[1, x, x², …, x^(n−1)]`."""
    return list(accumulate(repeat(x, n), lambda a, _: a * x, initial=ONE))[:n]


# 448 raw Poseidon1-KoalaBear width-16 round constants generated by the Grain
# LFSR (Poseidon paper §5.3, parameters field_type=1, α=3, n=31, t=16, R_F=8,
# R_P=20). Reference: https://github.com/Plonky3/Plonky3/blob/main/poseidon1/generate_constants.py
# Layout: 4 initial-full rounds × 16 + 20 partial rounds × 16 + 4 terminal-full rounds × 16.
def _grain_lfsr_round_constants_16() -> tuple[int, ...]:
    bits_msb = lambda v, w: [(v >> (w - 1 - i)) & 1 for i in range(w)]
    state = bits_msb(1, 2) + bits_msb(0, 4) + bits_msb(31, 12) + bits_msb(16, 12) + bits_msb(8, 10) + bits_msb(20, 10) + [1] * 30  # fmt: skip

    def step() -> int:
        nonlocal state
        new = state[62] ^ state[51] ^ state[38] ^ state[23] ^ state[13] ^ state[0]
        state = state[1:] + [new]
        return new

    for _ in range(160):  # spec-mandated warm-up
        step()

    def next_bit() -> int:  # self-shrinking generator: keep step()'s output only when the prior step was 1
        while True:
            if step() == 1:
                return step()
            step()

    def next_fe() -> int:  # rejection sampling into [0, P)
        while True:
            x = 0
            for _ in range(31):
                x = (x << 1) | next_bit()
            if x < P:
                return x

    return tuple(next_fe() for _ in range((8 + 20) * 16))


P1_ROUND_CONSTANTS_16: Final = _grain_lfsr_round_constants_16()


class Poseidon1Params:
    """Parameters for a Poseidon1 instance."""

    __slots__ = ("width", "rounds_f", "rounds_p", "mds_first_row", "round_constants")

    def __init__(
        self,
        width: int,
        rounds_f: int,
        rounds_p: int,
        mds_first_row: Sequence[int],
        round_constants: Sequence[int],
    ) -> None:
        assert len(mds_first_row) == width
        assert len(round_constants) == (rounds_f + rounds_p) * width
        self.width = width
        self.rounds_f = rounds_f
        self.rounds_p = rounds_p
        self.mds_first_row = mds_first_row
        self.round_constants = round_constants


class Poseidon1:
    """Pure-Python Poseidon1 permutation (S-box: x → x^3; dense circulant MDS).

    Round structure: AddRoundConstants → S-box (full state for full rounds, only
    position 0 for partial rounds) → MDS multiply.
    """

    __slots__ = ("_width", "_half_rounds_f", "_rounds_p", "_mds", "_rc")

    def __init__(self, params: Poseidon1Params) -> None:
        self._width = params.width
        self._half_rounds_f = params.rounds_f // 2
        self._rounds_p = params.rounds_p
        n = params.width
        # Build circulant MDS: M[i][j] = first_row[(j - i) mod n].
        self._mds = [[params.mds_first_row[(j - i) % n] for j in range(n)] for i in range(n)]
        self._rc = list(params.round_constants)

    def permute(self, current_state: Sequence[Fp]) -> list[Fp]:
        assert len(current_state) == self._width
        s = [x.value for x in current_state]
        w, p, mds, rc = self._width, P, self._mds, self._rc
        idx = 0

        def mds_mul() -> None:
            new = [sum((mds[i][j] * s[j]) % p for j in range(w)) % p for i in range(w)]
            s[:] = new

        for _ in range(self._half_rounds_f):
            for i in range(w):
                s[i] = (s[i] + rc[idx + i]) % p
            idx += w
            for i in range(w):
                s[i] = (s[i] * s[i] % p) * s[i] % p
            mds_mul()
        for _ in range(self._rounds_p):
            for i in range(w):
                s[i] = (s[i] + rc[idx + i]) % p
            idx += w
            s[0] = (s[0] * s[0] % p) * s[0] % p
            mds_mul()
        for _ in range(self._half_rounds_f):
            for i in range(w):
                s[i] = (s[i] + rc[idx + i]) % p
            idx += w
            for i in range(w):
                s[i] = (s[i] * s[i] % p) * s[i] % p
            mds_mul()

        return [Fp(v) for v in s]


PARAMS_16 = Poseidon1Params(
    width=16,
    rounds_f=8,
    rounds_p=20,
    mds_first_row=MDS_FIRST_ROW_16,
    round_constants=P1_ROUND_CONSTANTS_16,
)
"""Poseidon1 parameters for width-16 (8 full rounds, 20 partial)."""


POSEIDON16 = Poseidon1(PARAMS_16)


def poseidon16_compress(left: Sequence[Fp], right: Sequence[Fp]) -> list[Fp]:
    state = list(left) + list(right)
    assert len(state) == SPONGE_STATE
    return [a + b for a, b in zip(POSEIDON16.permute(state), state)][:DIGEST_ELEMS]


def log2_ceil(x: int) -> int:
    return 0 if x <= 1 else (x - 1).bit_length()


def log2_strict(x: int) -> int:
    assert x > 0 and (x & (x - 1)) == 0, f"{x} is not a power of two"
    return x.bit_length() - 1


def next_multiple_of(n: int, k: int) -> int:
    return (n + k - 1) // k * k


# ---------------------------------------------------------------------------
# Poseidon1 AIR partial-round constants (natural formulation).
# ---------------------------------------------------------------------------

POSEIDON1_AIR_CONSTANTS = {
    "half_full_rounds": PARAMS_16.rounds_f // 2,
    "partial_rounds": PARAMS_16.rounds_p,
    "partial_round_constants": [
        list(PARAMS_16.round_constants[(PARAMS_16.rounds_f // 2 + i) * PARAMS_16.width :
                                       (PARAMS_16.rounds_f // 2 + i + 1) * PARAMS_16.width])
        for i in range(PARAMS_16.rounds_p)
    ],
}
