[package]
name = "xmss"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["ssz"]
ssz = ["dep:ssz"]
test-utils = ["dep:postcard"]

[dependencies]
rand.workspace = true
backend.workspace = true
serde.workspace = true
postcard = { workspace = true, optional = true }
ssz = { workspace = true, optional = true }

[dev-dependencies]
postcard.workspace = true