[package]
name = "fiat-shamir"
version.workspace = true
edition.workspace = true

[dependencies]
field = { path = "../field", package = "field" }
goldilocks = { path = "../goldilocks", package = "goldilocks" }
symetric = { path = "../symetric", package = "symetric" }
utils = { path = "../utils", package = "utils" }
serde.workspace = true
parallel.workspace = true
