//! Prints an [`IntermediateProgram`] back to `.py` source (valid intermediate
//! zkDSL, re-parseable by the regular parser). Total, since the intermediate
//! AST cannot represent anything outside the subset.

use crate::intermediate_program::{
    IntermediateExpr, IntermediateFunction, IntermediateLine, IntermediateOp, IntermediateProgram, IntermediateTarget,
};
use lean_vm::BooleanExpr;
use std::fmt::Write;

const INDENT: &str = "    ";

pub fn intermediate_program_to_source(program: &IntermediateProgram) -> String {
    let mut out = String::new();
    out.push_str("# Intermediate zkDSL program, auto-generated by the first compilation stage.\n\n");
    // `main` first (cosmetic), then the rest in BTreeMap order.
    let main_first = program
        .functions
        .values()
        .filter(|f| f.name == "main")
        .chain(program.functions.values().filter(|f| f.name != "main"));
    for (i, function) in main_first.enumerate() {
        if i > 0 {
            out.push('\n');
        }
        write_function(function, &mut out);
    }
    out
}

fn write_function(function: &IntermediateFunction, out: &mut String) {
    let _ = write!(out, "def {}(", function.name);
    for (i, arg) in function.arguments.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(arg);
    }
    out.push_str("):\n");
    write_block(&function.body, 1, out);
}

fn push_indent(out: &mut String, indent: usize) {
    for _ in 0..indent {
        out.push_str(INDENT);
    }
}

/// Emits `assert 0 == 0` for an otherwise-empty block: the indentation-based
/// syntax cannot express an empty block, and the no-op is dropped at compile time.
fn write_block(lines: &[IntermediateLine], indent: usize, out: &mut String) {
    if !block_has_printable_statement(lines) {
        push_indent(out, indent);
        out.push_str("assert 0 == 0\n");
        return;
    }
    for line in lines {
        write_line(line, indent, out);
    }
}

fn write_line(line: &IntermediateLine, indent: usize, out: &mut String) {
    if matches!(line, IntermediateLine::LocationReport { .. }) {
        return;
    }
    push_indent(out, indent);
    match line {
        IntermediateLine::LocationReport { .. } => unreachable!(),
        IntermediateLine::Declaration { var } => {
            let _ = writeln!(out, "{var}: Imm");
        }
        IntermediateLine::Statement { targets, value, .. } => {
            for (i, target) in targets.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_target(target, out);
            }
            if !targets.is_empty() {
                out.push_str(" = ");
            }
            write_expr(value, out);
            out.push('\n');
        }
        IntermediateLine::Assert {
            debug,
            boolean,
            location: _,
        } => {
            if *debug {
                out.push_str("debug_assert(");
                write_boolean(boolean, out);
                out.push_str(")\n");
            } else {
                out.push_str("assert ");
                write_boolean(boolean, out);
                out.push('\n');
            }
        }
        IntermediateLine::IfCondition {
            condition,
            then_branch,
            else_branch,
            ..
        } => {
            out.push_str("if ");
            write_boolean(condition, out);
            out.push_str(":\n");
            write_block(then_branch, indent + 1, out);
            if block_has_printable_statement(else_branch) {
                push_indent(out, indent);
                out.push_str("else:\n");
                write_block(else_branch, indent + 1, out);
            }
        }
        IntermediateLine::Match { value, arms, .. } => {
            out.push_str("match ");
            write_expr(value, out);
            out.push_str(":\n");
            for (pattern, arm) in arms {
                push_indent(out, indent + 1);
                let _ = writeln!(out, "case {pattern}:");
                write_block(arm, indent + 2, out);
            }
        }
        IntermediateLine::ForLoop {
            iterator,
            start,
            end,
            body,
            parallel,
            ..
        } => {
            let range_fn = if *parallel { "parallel_range" } else { "range" };
            let _ = write!(out, "for {iterator} in {range_fn}(");
            write_expr(start, out);
            out.push_str(", ");
            write_expr(end, out);
            out.push_str("):\n");
            write_block(body, indent + 1, out);
        }
        IntermediateLine::FunctionRet { return_data } => {
            out.push_str("return");
            for (i, expr) in return_data.iter().enumerate() {
                out.push_str(if i == 0 { " " } else { ", " });
                write_expr(expr, out);
            }
            out.push('\n');
        }
        IntermediateLine::Panic { message } => match message {
            // No escape sequences in string literals, so `"` -> `'`.
            Some(msg) => {
                let _ = writeln!(out, "assert False, \"{}\"", msg.replace('"', "'"));
            }
            None => out.push_str("assert False\n"),
        },
    }
}

fn block_has_printable_statement(lines: &[IntermediateLine]) -> bool {
    lines
        .iter()
        .any(|line| !matches!(line, IntermediateLine::LocationReport { .. }))
}

fn write_target(target: &IntermediateTarget, out: &mut String) {
    match target {
        IntermediateTarget::Var(var) => out.push_str(var),
        IntermediateTarget::ArrayAccess { array, index } => {
            out.push_str(array);
            out.push('[');
            write_expr(index, out);
            out.push(']');
        }
    }
}

fn write_boolean(boolean: &BooleanExpr<IntermediateExpr>, out: &mut String) {
    write_expr(&boolean.left, out);
    let _ = write!(out, " {} ", boolean.kind);
    write_expr(&boolean.right, out);
}

fn write_expr(expr: &IntermediateExpr, out: &mut String) {
    match expr {
        IntermediateExpr::Var(var) => out.push_str(var),
        IntermediateExpr::Constant(scalar) => {
            let _ = write!(out, "{scalar}");
        }
        IntermediateExpr::ArrayAccess { array, index } => {
            out.push_str(array);
            out.push('[');
            write_expr(index, out);
            out.push(']');
        }
        IntermediateExpr::Math { op, left, right } => {
            // Fully parenthesized, but a left-nested chain of the same operator
            // is printed FLAT: `(a OP b OP c)` re-parses identically (the parser
            // folds left-associatively) but as one recursion level instead of
            // one per term, which would overflow the parser stack on long chains.
            let mut chain = vec![right.as_ref()];
            let mut head = left.as_ref();
            loop {
                match head {
                    IntermediateExpr::Math {
                        op: inner_op,
                        left: inner_left,
                        right: inner_right,
                    } if inner_op == op => {
                        chain.push(inner_right.as_ref());
                        head = inner_left.as_ref();
                    }
                    _ => break,
                }
            }
            chain.push(head);
            let op_str = match op {
                IntermediateOp::Add => " + ",
                IntermediateOp::Sub => " - ",
                IntermediateOp::Mul => " * ",
                IntermediateOp::Div => " / ",
            };
            out.push('(');
            for (i, operand) in chain.iter().rev().enumerate() {
                if i > 0 {
                    out.push_str(op_str);
                }
                write_expr(operand, out);
            }
            out.push(')');
        }
        IntermediateExpr::FunctionCall { function, args, .. } => {
            out.push_str(function);
            out.push('(');
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_expr(arg, out);
            }
            out.push(')');
        }
        IntermediateExpr::HintWitness { name, ptr } => {
            let _ = write!(out, "hint_witness(\"{name}\", ");
            write_expr(ptr, out);
            out.push(')');
        }
    }
}
